
team_to_abr_conversion = {
    "New Orleans Pelicans": "NOP",
    "Golden State Warriors": "GSW",
    "Los Angeles Clippers": "LAC",
    "Milwaukee Bucks": "MIL",
    "Toronto Raptors": "TOR",
    "Brooklyn Nets": "BRK",
    "Philadelphia 76ers": "PHI",
    "San Antonio Spurs": "SAS",
    "Oklahoma City Thunder": "OKC",
    "Washington Wizards": "WAS",
    "Boston Celtics": "BOS",
    "Sacramento Kings": "SAC",
    "Portland Trail Blazers": "POR",
    "Houston Rockets": "HOU",
    "Atlanta Hawks": "ATL",
    "Minnesota Timberwolves": "MIN",
    "Los Angeles Lakers": "LAL",
    "Charlotte Hornets": "CHO",
    "Denver Nuggets": "DEN",
    "Indiana Pacers": "IND",
    "Dallas Mavericks": "DAL",
    "Utah Jazz": "UTA",
    "Phoenix Suns": "PHO",
    "Orlando Magic": "ORL",
    "New York Knicks": "NYK",
    "Chicago Bulls": "CHI",
    "Detroit Pistons": "DET",
    "Memphis Grizzlies": "MEM",
    "Miami Heat": "MIA",
    "Cleveland Cavaliers": "CLE",

    #City to abreviation
    "New Orleans": "NOP",
    "Golden State": "GSW",
    "LA Clippers": "LAC",
    "Milwaukee": "MIL",
    "Toronto": "TOR",
    "Brooklyn": "BRK",
    "Philadelphia": "PHI",
    "San Antonio": "SAS",
    "Oklahoma City": "OKC",
    "Washington": "WAS",
    "Boston": "BOS",
    "Sacramento": "SAC",
    "Portland": "POR",
    "Houston": "HOU",
    "Atlanta": "ATL",
    "Minnesota": "MIN",
    "LA Lakers": "LAL",
    "Charlotte": "CHO",
    "Denver": "DEN",
    "Indiana": "IND",
    "Dallas": "DAL",
    "Utah": "UTA",
    "Phoenix": "PHO",
    "Orlando": "ORL",
    "New York": "NYK",
    "Chicago": "CHI",
    "Detroit": "DET",
    "Memphis": "MEM",
    "Miami": "MIA",
    "Cleveland": "CLE"
    }

team_to_full_conversion = {
    "NOP":"New Orleans Pelicans",
    "GSW":"Golden State Warriors",
    "LAC":"Los Angeles Clippers",
    "MIL":"Milwaukee Bucks",
    "TOR":"Toronto Raptors",
    "BKN":"Brooklyn Nets",
    "PHI":"Philadelphia 76ers",
    "SAS":"San Antonio Spurs",
    "OKC":"Oklahoma City Thunder",
    "WAS":"Washington Wizards",
    "BOS":"Boston Celtics",
    "SAC":"Sacramento Kings",
    "POR":"Portland Trail Blazers",
    "HOU":"Houston Rockets",
    "ATL":"Atlanta Hawks",
    "MIN":"Minnesota Timberwolves",
    "LAL":"Los Angeles Lakers",
    "CHA":"Charlotte Hornets",
    "DEN":"Denver Nuggets",
    "IND":"Indiana Pacers",
    "DAL":"Dallas Mavericks",
    "UTA":"Utah Jazz",
    "PHO":"Phoenix Suns",
    "PHX":"Phoenix Suns",
    "ORL":"Orlando Magic",
    "NYK":"New York Knicks",
    "CHI":"Chicago Bulls",
    "DET":"Detroit Pistons",
    "MEM":"Memphis Grizzlies",
    "MIA":"Miami Heat",
    "CLE":"Cleveland Cavaliers",

    "New Orleans":"New Orleans Pelicans",
    "Golden State":"Golden State Warriors",
    "LA Clippers":"Los Angeles Clippers",
    "Milwaukee":"Milwaukee Bucks",
    "Toronto":"Toronto Raptors",
    "Brooklyn":"Brooklyn Nets",
    "Philadelphia":"Philadelphia 76ers",
    "San Antonio":"San Antonio Spurs",
    "Oklahoma City":"Oklahoma City Thunder",
    "Washington":"Washington Wizards",
    "Boston":"Boston Celtics",
    "Sacramento":"Sacramento Kings",
    "Portland":"Portland Trail Blazers",
    "Houston":"Houston Rockets",
    "Atlanta":"Atlanta Hawks",
    "Minnesota":"Minnesota Timberwolves",
    "LA Lakers":"Los Angeles Lakers",
    "Charlotte":"Charlotte Hornets",
    "Denver":"Denver Nuggets",
    "Indiana":"Indiana Pacers",
    "Dallas":"Dallas Mavericks",
    "Utah":"Utah Jazz",
    "Phoenix":"Phoenix Suns",
    "Orlando":"Orlando Magic",
    "New York":"New York Knicks",
    "Chicago":"Chicago Bulls",
    "Detroit":"Detroit Pistons",
    "Memphis":"Memphis Grizzlies",
    "Miami":"Miami Heat",
    "Cleveland":"Cleveland Cavaliers"
    }

team_to_city_conversion = {
    "NOP":"New Orleans",
    "GSW":"Golden State",
    "LAC":"LA Clippers",
    "MIL":"Milwaukee",
    "TOR":"Toronto",
    "BKN":"Brooklyn",
    "BRK":"Brooklyn",
    "PHI":"Philadelphia",
    "SAS":"San Antonio",
    "OKC":"Oklahoma City",
    "WAS":"Washington",
    "BOS":"Boston",
    "SAC":"Sacramento",
    "POR":"Portland",
    "HOU":"Houston",
    "ATL":"Atlanta",
    "MIN":"Minnesota",
    "LAL":"LA Lakers",
    "CHA":"Charlotte",
    "CHO":"Charlotte",
    "DEN":"Denver",
    "IND":"Indiana",
    "DAL":"Dallas",
    "UTA":"Utah",
    "PHO":"Phoenix",
    "PHX":"Phoenix",
    "ORL":"Orlando",
    "NYK":"New York",
    "CHI":"Chicago",
    "DET":"Detroit",
    "MEM":"Memphis",
    "MIA":"Miami",
    "CLE":"Cleveland",


    "New Orleans Pelicans":"New Orleans",
    "Golden State Warriors":"Golden State",
    "Los Angeles Clippers":"LA Clippers",
    "LA Clippers":"LA Clippers",
    "Milwaukee Bucks":"Milwaukee",
    "Toronto Raptors":"Toronto",
    "Brooklyn Nets":"Brooklyn",
    "Philadelphia 76ers":"Philadelphia",
    "San Antonio Spurs":"San Antonio",
    "Oklahoma City Thunder":"Oklahoma City",
    "Washington Wizards":"Washington",
    "Boston Celtics":"Boston",
    "Sacramento Kings":"Sacramento",
    "Portland Trail Blazers":"Portland",
    "Houston Rockets":"Houston",
    "Atlanta Hawks":"Atlanta",
    "Minnesota Timberwolves":"Minnesota",
    "Los Angeles Lakers":"LA Lakers",
    "LA Lakers":"LA Lakers",
    "Charlotte Hornets":"Charlotte",
    "Denver Nuggets":"Denver",
    "Indiana Pacers":"Indiana",
    "Dallas Mavericks":"Dallas",
    "Utah Jazz":"Utah",
    "Phoenix Suns":"Phoenix",
    "Orlando Magic":"Orlando",
    "New York Knicks":"New York",
    "Chicago Bulls":"Chicago",
    "Detroit Pistons":"Detroit",
    "Memphis Grizzlies":"Memphis",
    "Miami Heat":"Miami",
    "Cleveland Cavaliers":"Cleveland"
    }

team_to_id_conversion = {
    "Atlanta" : 1,
    "Boston" : 2,
    "Brooklyn" :3,
    "Charlotte":4,
    "Chicago":5,
    "Cleveland":6,
    "Dallas":7,
    "Denver":8,
    "Detroit":9,
    "Golden State":10,
    "Houston":11,
    "Indiana":12,
    "LA Clippers":13,
    "LA Lakers":14,
    "Memphis":15,
    "Miami":16,
    "Milwaukee":17,
    "Minnesota": 18,
    "New Orleans": 19,
    "New York": 20,
    "Oklahoma City":21,
    "Orlando":22,
    "Philadelphia":23,
    "Phoenix":24,
    "Portland":25,
    "Sacramento":26,
    "San Antonio":27,
    "Toronto":28,
    "Utah":29,
    "Washington":30
}

id_to_team_conversion = {
    1:"Atlanta",
    2:"Boston",
    3:"Brooklyn",
    4:"Charlotte",
    5:"Chicago",
    6:"Cleveland",
    7:"Dallas",
    8:"Denver",
    9:"Detroit",
    10:"Golden State",
    11:"Houston",
    12:"Indiana",
    13:"LA Clippers",
    14:"LA Lakers",
    15:"Memphis",
    16:"Miami",
    17:"Milwaukee",
    18:"Minnesota",
    19:"New Orleans",
    20:"New York",
    21:"Oklahoma City",
    22:"Orlando",
    23:"Philadelphia",
    24:"Phoenix",
    25:"Portland",
    26:"Sacramento",
    27:"San Antonio",
    28:"Toronto",
    29:"Utah",
    30:"Washington"
}


def team_to_abr(team):
    return team_to_abr_conversion.get(team, team)


def team_to_full(team):
    return team_to_full_conversion.get(team, team)


def team_to_city(team):
    return team_to_city_conversion.get(team, team)


def team_to_id(team):
    city = team_to_city(team)
    return team_to_id_conversion[city]


def id_to_team(id):
    return id_to_team_conversion[id]

